/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GraphHandler } from "./globals/graphHandler";
export namespace Components {
    interface WcGenesPanel {
        "ghandler": GraphHandler;
    }
    interface WcGocamViz {
        "autoHideModal": boolean;
        "gocamId": string;
        "graphFold": string;
        "showActivity": boolean;
        "showGeneProduct": boolean;
        "showHasInput": boolean;
        "showHasOutput": boolean;
    }
}
declare global {
    interface HTMLWcGenesPanelElement extends Components.WcGenesPanel, HTMLStencilElement {
    }
    var HTMLWcGenesPanelElement: {
        prototype: HTMLWcGenesPanelElement;
        new (): HTMLWcGenesPanelElement;
    };
    interface HTMLWcGocamVizElement extends Components.WcGocamViz, HTMLStencilElement {
    }
    var HTMLWcGocamVizElement: {
        prototype: HTMLWcGocamVizElement;
        new (): HTMLWcGocamVizElement;
    };
    interface HTMLElementTagNameMap {
        "wc-genes-panel": HTMLWcGenesPanelElement;
        "wc-gocam-viz": HTMLWcGocamVizElement;
    }
}
declare namespace LocalJSX {
    interface WcGenesPanel {
        "ghandler"?: GraphHandler;
        "onSelectChanged"?: (event: CustomEvent<any>) => void;
    }
    interface WcGocamViz {
        "autoHideModal"?: boolean;
        "gocamId"?: string;
        "graphFold"?: string;
        "onLayoutChange"?: (event: CustomEvent<any>) => void;
        "onNodeClick"?: (event: CustomEvent<any>) => void;
        "onNodeOut"?: (event: CustomEvent<any>) => void;
        "onNodeOver"?: (event: CustomEvent<any>) => void;
        "showActivity"?: boolean;
        "showGeneProduct"?: boolean;
        "showHasInput"?: boolean;
        "showHasOutput"?: boolean;
    }
    interface IntrinsicElements {
        "wc-genes-panel": WcGenesPanel;
        "wc-gocam-viz": WcGocamViz;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-genes-panel": LocalJSX.WcGenesPanel & JSXBase.HTMLAttributes<HTMLWcGenesPanelElement>;
            "wc-gocam-viz": LocalJSX.WcGocamViz & JSXBase.HTMLAttributes<HTMLWcGocamVizElement>;
        }
    }
}
